# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65a60eac5da09c77d80f6f3ee11fa63ad6eeebab588682673dd9818ac4adb5b5954730b415172719a28097b90eaaeef1e20d106a4388fc1809377d71cf180391

test:
  secret_key_base: 7440b9202c953ec06cd18230a822c2ff22cc10bfc89db1e7620be00723d4d95f1aecfd30e79dc98f993e7621f8ffa903429b1a379fd5d1453a0cfa0fd34651c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
