# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bc9b5611cf6770e1060584850d04080f9330d2e2bff9f17cf8d0d4c56e3ff3607305ba7ae1928c99fd48267c2b6df157e784a84665681fcf9839ba0bf6d901a

test:
  secret_key_base: ad069475b321f917d4e9fe0251f97a3fc5170e4adc73dc510dfbc6080ebe9961a4846cd911b001357767900e110f7db7bd8802327a0c024c208b1bb0e7e95a15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
