# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6e61a0de9a5618c64679a0c5c01ca72366d7c9af5aef42bdbe055f604673cf71166cb12c8ad6506bfcd8ffc2215d0fc632499516d164f1d8b63ada839e99ce4

test:
  secret_key_base: 284478b890445dea6585a2adf00f20f16dd429b968b7577d112a49a1fdeaed20f46b5e0b71a7c5e30f5120b3badc5714ba1187b3da5827042688654e275ca054

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
