task :default => 'morning:get_ready'

namespace :morning do
  desc "Turn off the God damn alarm"
  task :turn_off_alarm do
    puts "alarm disabled"
  end
  desc "Making me look spanking"
  task :groom_self do
    puts "brush teeth"
    puts "comb beard"
    puts "style underarms"
    puts "Hatch a grogan"
  end

  desc "pour the drug for the day"
  task :make_coffee do
    cups = ENV['COFFEE_CUPS'] || 2
    puts " Made #{cups} cups of coffee. God give me strength."
  end

  #in bash COFFEE_CUPS=12 rake make_coffee
  desc "animal exercise"
  task :walk_horrible_dog do
    puts "walking the horrible dog"
  end

  desc "run it all, run it all the get ready day program"
  task :get_ready => [:turn_off_alarm, :groom_self, :make_coffee, :walk_horrible_dog] do
    puts "Now ready for the day"
  end
end

namespace :morning do
  task :groom_self do
    puts "FAUX HAWK"
  end
end

#adding a new task to it by reopening the namespace

namespace :afternoon do
  task :make_coffee do
    Rake::Task['morning:make_coffee'].invoke
    puts "ready for the afternoon"
  end
end

# directory "tmp"

# file "hello" => "tmp" do
#   sh "echo 'Hello' >> tmp/Hello"
# end

