# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e52b85eefaf2e4dbf2c38019920957f660009c499290aa79cfa93eb4fc1c42939d4f0d40ea260672d7b1106dd34dcc6ce242495baced7350b4642194d576db34

test:
  secret_key_base: fe715cb16295b06a34f215cecc9e7295b1fdf31179e31228d255505de03598d23fec36215d3ef0b5852bcc43a68af01ca47ec3d9b7354ab04f97225ad16b3033

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
