# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 904087fd8dd04bc8715fc022decf83a6ef672c3ae49455dd7dad6a2dd34fd2de106259515463a706dd2d99a275e70aedc946654f7876f80f9702871a11bd0fce

test:
  secret_key_base: ad95da0e73213980d5b409312da6c32a162c846087b734b55644f779143d763bd72a56435be6e6b284c22bffbf28d882135f535fd19b4e162e681de168655f32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
